export type Product = {
  id: number,
      type: string,
      context: string,
      price: number,
      description: string,
      image: string,
      active: true,
      season: string,
      brand: string,
      tread: string,
      stock: number,
      width: number,
      profile: number,
      diameter: number,
}